root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
pre_cmd = []
cmd = ""
post_cmd = []
bin = "/usr/bin/make build-run"
full_bin = ""
args_bin = []
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 1000 # ms
delay = 2000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 1000 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
proxy_port = 8090
app_port = 8080