services:
  postgres:
    container_name: example_go_postgres
    image: 'postgres:14-alpine'
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=example_go
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=secret
    volumes:
      - "~/backup/db/postgres/example-go:/var/lib/postgresql/data"

  redis:
    container_name: example_go_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  consul:
    container_name: example_go_consul
    image: consul:latest
    ports:
      - "8500:8500"